Skip Nvidia/Cuda tests if installation is disabled
Signed-off-by: Luca Carrogu <carrogu@amazon.com>

diff --git a/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml b/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
--- a/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
+++ b/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
@@ -22,8 +22,7 @@ phases:
                 . ${FILE}
                 echo "${ID}${VERSION_ID:+.${VERSION_ID}}"
               else
-                echo "The file '${FILE}' does not exist. Failing build."
-                exit 1
+                echo "The file '${FILE}' does not exist. Failing build." && exit 1
               fi
 
       # Get uniformed OS name
@@ -46,8 +45,7 @@ phases:
               elif [ `echo "${RELEASE}" | grep '^ubuntu\.20'` ]; then
                 OS='ubuntu2004'
               else
-                echo "Operating System '${RELEASE}' is not supported. Failing build."
-                exit 1
+                echo "Operating System '${RELEASE}' is not supported. Failing build." && exit 1
               fi
 
               echo ${OS}
@@ -68,8 +66,7 @@ phases:
                   echo 'arm64'
                   ;;
                 *)
-                  echo "The '${ARCH}' architecture is not supported. Failing build."
-                  exit 1
+                  echo "The '${ARCH}' architecture is not supported. Failing build." && exit 1
                   ;;
               esac
 
@@ -102,18 +99,14 @@ phases:
               AWS_REGION=${AVAIL_ZONE::-1}
               echo ${AWS_REGION}
 
-      ### condition ###
+      ### conditions ###
       - name: IntelMPISupported
         action: ExecuteBash
         inputs:
           commands:
             - |
               set -v
-              if [ {{ validate.OperatingSystemArchitecture.outputs.stdout }} != 'arm64' ]; then
-                echo "true"
-              else
-                echo "false"
-              fi
+              [[ {{ validate.OperatingSystemArchitecture.outputs.stdout }} != 'arm64' ]] && echo "true" || echo "false"
 
       - name: ArmPLSupported
         action: ExecuteBash
@@ -121,11 +114,7 @@ phases:
           commands:
             - |
               set -v
-              if [ {{ validate.OperatingSystemArchitecture.outputs.stdout }} == 'arm64' ]; then
-                echo "true"
-              else
-                echo "false"
-              fi
+              [[ {{ validate.OperatingSystemArchitecture.outputs.stdout }} == 'arm64' ]] && echo "true" || echo "false"
 
       - name: LustreSupported
         action: ExecuteBash
@@ -141,7 +130,7 @@ phases:
                 echo "false"
               fi
 
-      ### version ###
+      ### versions ###
       - name: PythonVersion
         action: ExecuteBash
         inputs:
@@ -207,16 +196,34 @@ phases:
               echo ${VERSION}
 
       ### utils ###
+      - name: NvidiaEnabled
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              set -v
+              NVIDIA_ENABLED=$(cat /etc/parallelcluster/image_dna.json | jq -r '.cluster.nvidia.enabled')
+              echo "${NVIDIA_ENABLED}"
+
+      - name: HasGPU
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              set -v
+              HAS_GPU=$(lspci | grep -o "NVIDIA") || HAS_GPU="false"
+              echo "${HAS_GPU}"
+
       - name: NvSwitches
         action: ExecuteBash
         inputs:
           commands:
             - |
               set -v
-              nvswitches=$(lspci -d 10de:1af1 | wc -l)
-              echo "$nvswitches"
+              NVSWITCHES=$(lspci -d 10de:1af1 | wc -l)
+              echo "${NVSWITCHES}"
 
-      ### path ###
+      ### paths ###
       - name: SystemPyenvRoot
         action: ExecuteBash
         inputs:
@@ -244,8 +251,7 @@ phases:
               set -v
               echo "{{ validate.SystemPyenvRoot.outputs.stdout }}/versions/{{ validate.PythonVersion.outputs.stdout }}/envs/node_virtualenv"
 
-      ### validate ###
-      # AWS CLI
+      ### validations ###
       - name: AWSCli
         action: ExecuteBash
         inputs:
@@ -262,27 +268,25 @@ phases:
               fi
               export PATH="/usr/local/bin:/usr/bin/:${PATH}"
 
-              echo "execute awscli as user"
+              echo "Executing awscli as user..."
               su - ${username} -c "aws --version"
 
-              echo "execute awscli as root"
+              echo "Executing awscli as root..."
               aws --version
               [[ $? -ne 0 ]] && echo "fail to execute awscli as root" && exit 1
 
-              echo "execute awscli as root in cookbook virtualenv"
+              echo "Executing awscli as root in cookbook virtualenv.."
               {{ validate.CookbookVirtualenvPath.outputs.stdout }}/bin/aws --version
               [[ $? -ne 0 ]] && echo "fail to execute awscli as root in cookbook virtualenv" && exit 1
 
-              echo "check virtualenv python version"
+              echo "Checking virtualenv python version..."
               {{ validate.CookbookVirtualenvPath.outputs.stdout }}/bin/python -V | grep {{ validate.PythonVersion.outputs.stdout }}
-              [[ $? -ne 0 ]] && echo "check cookbook virtualenv python version failed" && exit 1
+              [[ $? -ne 0 ]] && echo "Check cookbook virtualenv python version failed" && exit 1
 
               {{ validate.NodeVirtualenvPath.outputs.stdout }}/bin/python -V | grep {{ validate.PythonVersion.outputs.stdout }}
-              [[ $? -ne 0 ]] && echo "check node virtualenv python version failed" && exit 1
+              [[ $? -ne 0 ]] && echo "Check node virtualenv python version failed" && exit 1
+              echo "AWSCli test passed"
 
-              echo "pass awscli test"
-
-      # Munge
       - name: Munge
         action: ExecuteBash
         inputs:
@@ -291,11 +295,9 @@ phases:
               set -vx
               echo "check munge installed"
               munge --version | grep {{ validate.MungeVersion.outputs.stdout }}
-              [[ $? -ne 0 ]] && echo "check munge version failed" && exit 1
+              [[ $? -ne 0 ]] && echo "Check munge version failed" && exit 1
+              echo "Munge test passed"
 
-              echo "pass munge test"
-
-      # EFA - Intel MPI
       - name: EFAIntelMPI
         action: ExecuteBash
         inputs:
@@ -305,51 +307,42 @@ phases:
               PLATFORM='{{ validate.PlatformName.outputs.stdout }}'
 
               if [ {{ validate.IntelMPISupported.outputs.stdout }} == true ]; then
+                echo "Checking efa rpm installed..."
                 if [ ${PLATFORM} == RHEL ]; then
-                  echo "check efa rpm installed"
                   rpm -qa | grep libfabric && rpm -qa | grep efa-
-                  [[ $? -ne 0 ]] && echo "check efa rpm failed" && exit 1
+                  [[ $? -ne 0 ]] && echo "Check efa rpm failed" && exit 1
 
-                  echo "check intel mpi installed"
+                  echo "Checking intel mpi installed..."
                   rpm -qa | grep intel-mpi
-                  [[ $? -ne 0 ]] && echo "check intel mpi failed" && exit 1
+                  [[ $? -ne 0 ]] && echo "Check intel mpi failed" && exit 1
                 else
-                  echo "check efa rpm installed"
                   dpkg -l | grep libfabric && dpkg -l | grep 'efa '
-                  [[ $? -ne 0 ]] && echo "check efa rpm failed" && exit 1
+                  [[ $? -ne 0 ]] && echo "Check efa rpm failed" && exit 1
                 fi
               fi
+              echo "EFA test passed"
 
-              echo "pass EFA test"
-
-      # NVIDIA
       - name: Nvidia
         action: ExecuteBash
         inputs:
           commands:
             - |
               set -vx
-              has_gpu=$(lspci | grep -o "NVIDIA") || has_gpu="false"
-              if [ ${has_gpu} == false ]; then
-                echo "No GPU detected, no test needed."
-                exit 0
+              if [ {{ validate.NvidiaEnabled.outputs.stdout }} == "no" ]; then
+                echo "NVIDIA recipe not enabled, no test needed." && exit 0
+              fi
+              if [ {{ validate.HasGPU.outputs.stdout }} == "false" ]; then
+                echo "No GPU detected, no test needed." && exit 0
               fi
 
               driver_ver="{{ validate.NvidiaDriverVersion.outputs.stdout }}"
               export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin"
 
-              # Test NVIDIA Driver installation
               echo "Testing NVIDIA driver install..."
-              # grep driver version from nvidia-smi output. If driver is not installed nvidia-smi command will fail
               driver_output=$(nvidia-smi | grep -E -o "Driver Version: [0-9.]+")
-              if [ "${driver_output}" != "Driver Version: ${driver_ver}" ]; then
-                echo "NVIDIA driver installed incorrectly! Installed ${driver_output} but expected version ${driver_ver}"
-                exit 1
-              else
-                echo "Correctly installed NVIDIA ${driver_output}"
-              fi
+              [[ "${driver_output}" != "Driver Version: ${driver_ver}" ]] && "NVIDIA driver installed incorrectly! Installed ${driver_output} but expected version ${driver_ver}" && exit 1
+              echo "Correctly installed NVIDIA ${driver_output}"
 
-      # CUDA
       - name: Cuda
         action: ExecuteBash
         inputs:
@@ -359,47 +352,27 @@ phases:
               OS='{{ validate.OperatingSystemName.outputs.stdout }}'
 
               if [ ${OS} != "alinux2" ] || [ {{ validate.NvSwitches.outputs.stdout }} -lt 1 ]; then
-                has_gpu=$(lspci | grep -o "NVIDIA") || has_gpu="false"
-                if [ "${has_gpu}" == false ]; then
-                  echo "No GPU detected, no test needed."
-                  exit 0
+                if [ {{ validate.NvidiaEnabled.outputs.stdout }} == "no" ]; then
+                  echo "NVIDIA recipe not enabled, no test needed." && exit 0
+                fi
+                if [ {{ validate.HasGPU.outputs.stdout }} == "false" ]; then
+                  echo "No GPU detected, no test needed." && exit 0
                 fi
 
                 cuda_ver="{{ validate.CudaVersion.outputs.stdout }}"
-                # Test CUDA installation
                 echo "Testing CUDA install with nvcc..."
                 export PATH=/usr/local/cuda-${cuda_ver}/bin:${PATH}
                 export LD_LIBRARY_PATH=/usr/local/cuda-${cuda_ver}/lib64:${LD_LIBRARY_PATH}
-                # grep CUDA version from nvcc output. If CUDA is not installed nvcc command will fail
                 cuda_output=$(nvcc -V | grep -E -o "release [0-9]+.[0-9]+")
-                if [ "${cuda_output}" != "release ${cuda_ver}" ]; then
-                  echo "CUDA installed incorrectly! Installed ${cuda_output} but expected ${cuda_ver}"
-                  exit 1
-                else
-                  echo "CUDA nvcc test passed, $cuda_output"
-                fi
+                [[ "${cuda_output}" != "release ${cuda_ver}" ]] && echo "CUDA installed incorrectly! Installed ${cuda_output} but expected ${cuda_ver}" && exit 1
+                echo "CUDA nvcc test passed, $cuda_output"
 
-                # Test deviceQuery
                 echo "Testing CUDA install with deviceQuery..."
                 /usr/local/cuda-${cuda_ver}/extras/demo_suite/deviceQuery | grep -o "Result = PASS"
                 [[ $? -ne 0 ]] && echo "CUDA deviceQuery test failed" && exit 1
-                echo "CUDA deviceQuery test passed"
-                echo "Correctly installed CUDA ${cuda_output}"
+                echo "CUDA deviceQuery test passed. Correctly installed CUDA ${cuda_output}"
               fi
 
-      # CloudWatch
-      - name: CloudWatch
-        action: ExecuteBash
-        inputs:
-          commands:
-            - |
-              set -vx
-              /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status | grep status | grep stopped
-              [[ $? -ne 0 ]] && echo "amazon-cloudwatch-agent is not stopped" && exit 1
-
-              echo "pass CloudWatch test"
-
-      # FSx Lustre
       - name: FSxLustre
         action: ExecuteBash
         inputs:
@@ -409,19 +382,16 @@ phases:
               OS='{{ validate.OperatingSystemName.outputs.stdout }}'
 
               if [ {{ validate.LustreSupported.outputs.stdout }} == true ]; then
+                echo "Checking for Lustre client..."
                 if [ ${OS} == centos7 ]; then
-                  echo "check for lustre libraries"
                   rpm -qa | grep lustre-client
                 elif [ ${OS} == ubuntu1804 ]; then
-                  echo "check for lustre libraries"
                   dpkg -l | grep lustre
                 fi
               fi
-              [[ $? -ne 0 ]] && echo "check lustre libraries failed" && exit 1
+              [[ $? -ne 0 ]] && echo "Check for Lustre client failed" && exit 1
+              echo "FSx Lustre test passed"
 
-              echo "pass FSx test"
-
-      # PIP
       - name: PIP
         action: ExecuteBash
         inputs:
@@ -445,13 +415,9 @@ phases:
                 echo "pip version in cookbook virtualenv must be greater than 19.3" && exit 1
               fi
 
-              if [ $(compare_version "${NODE_PIP_VERSION}") == true ]; then
-                echo "pip version in node virtualenv must be greater than 19.3" && exit 1
-              fi
+              [[ $(compare_version "${NODE_PIP_VERSION}") == true ]] && echo "pip version in node virtualenv must be greater than 19.3" && exit 1
+              echo "Pip test passed"
 
-              echo "pass PIP test"
-
-      # ARM - PL
       - name: ArmPL
         action: ExecuteBash
         inputs:
@@ -459,37 +425,32 @@ phases:
             - |
               set -vx
               if [ {{ validate.ArmPLSupported.outputs.stdout }} == true ]; then
-                echo "check gcc version and module loaded"
-                # Initialize module
+                echo "Checking gcc version and module loaded..."
                 unset MODULEPATH
                 source /etc/profile.d/modules.sh
                 (module avail)2>&1 | grep armpl/{{ validate.ArmPLVersion.outputs.stdout }}
-                [[ $? -ne 0 ]] && echo "check armpl version failed" && exit 1
+                [[ $? -ne 0 ]] && echo "Check armpl version failed" && exit 1
                 module load armpl/{{ validate.ArmPLVersion.outputs.stdout }}
                 gcc --version | grep {{ validate.ArmPLGCCVersion.outputs.stdout }}
-                [[ $? -ne 0 ]] && echo "check gcc version for armpl failed" && exit 1
+                [[ $? -ne 0 ]] && echo "Check gcc version for armpl failed" && exit 1
                 (module list)2>&1 | grep armpl/{{ validate.ArmPLVersion.outputs.stdout }}_gcc-{{ validate.ArmPLGCCVersion.outputs.stdout }}
-                [[ $? -ne 0 ]] && echo "check armpl module failed" && exit 1
+                [[ $? -ne 0 ]] && echo "Check armpl module failed" && exit 1
                 (module list)2>&1 | grep armpl/gcc-{{ validate.ArmPLGCCVersion.outputs.stdout }}
-                [[ $? -ne 0 ]] && echo "check gcc module failed" && exit 1
+                [[ $? -ne 0 ]] && echo "Check gcc module failed" && exit 1
+                echo "ArmPL test passed"
               fi
 
-              echo "pass ArmPL test"
-
-      # Python
       - name: Python
         action: ExecuteBash
         inputs:
           commands:
             - |
               set -vx
-              echo "check python3 installed"
+              echo "Checking python3 installed..."
               which python3
               [[ $? -ne 0 ]] && echo "Python3 is not installed" && exit 1
+              echo "Python test passed"
 
-              echo "pass Python test"
-
-      # DPKG
       - name: DPKG
         action: ExecuteBash
         inputs:
@@ -497,12 +458,10 @@ phases:
             - |
               set -vx
               PLATFORM='{{ validate.PlatformName.outputs.stdout }}'
-              echo "check dpkg is not installed on non-debian OS"
               if [ ${PLATFORM} != DEBIAN ]; then
+                echo "Checking dpkg is not installed on non-debian OS..."
                 if command -v dpkg &> /dev/null; then
-                  echo "ERROR: dpkg found on non-Debian system"
-                  exit 1
+                  echo "ERROR: dpkg found on non-Debian system" && exit 1
                 fi
+                echo "dpkg test passed"
               fi
-
-              echo "pass DPKG test"
