Using Cookbook Virtual environment for installing latest cmake version and then using it for cuda device query and later uninstalling it

diff --git a/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml b/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
--- a/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
+++ b/cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
@@ -309,32 +309,44 @@ phases:
               echo "Correctly installed CUDA ${cuda_output}"
 
               echo "Testing CUDA with deviceQuery..."
-              if [ {{ validate.OperatingSystemName.outputs.stdout }} == 'ubuntu2004' ]; then
-                echo "Skipping CUDA deviceQuery test on Ubuntu 20.04"
+              if [ {{ validate.OperatingSystemArchitecture.outputs.stdout }} != 'arm64' ]; then
+                /usr/local/cuda-${cuda_ver}/extras/demo_suite/deviceQuery | grep -o "Result = PASS"
+                [[ $? -ne 0 ]] && echo "CUDA deviceQuery test failed" && exit 1
               else
-                if [ {{ validate.OperatingSystemArchitecture.outputs.stdout }} != 'arm64' ]; then
-                  /usr/local/cuda-${cuda_ver}/extras/demo_suite/deviceQuery | grep -o "Result = PASS"
-                  [[ $? -ne 0 ]] && echo "CUDA deviceQuery test failed" && exit 1
-                else
-                   cd /usr/local/{{ validate.CudaSamplesSrcDir.outputs.stdout }}/1_Utilities/deviceQuery
-                   if [ {{ validate.OperatingSystemName.outputs.stdout }} == 'alinux2' ]; then
-                     make
-                     /usr/local/{{ validate.CudaSamplesBinDir.outputs.stdout }}/sbsa/linux/release/deviceQuery | grep -o "Result = PASS"
-                   else
-                     mkdir build
-                     cd build
-                     cmake .. \
-                      -DCMAKE_CUDA_ARCHITECTURES="75;80;86" \
-                      -DCMAKE_CUDA_COMPILER=/usr/local/cuda-${cuda_ver}/bin/nvcc \
-                      -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-${cuda_ver} \
-                      -DCMAKE_PREFIX_PATH=/usr/local/cuda-cuda-${cuda_ver}
-                     make
-                     ./deviceQuery | grep -o "Result = PASS"
+                 cd /usr/local/{{ validate.CudaSamplesSrcDir.outputs.stdout }}/1_Utilities/deviceQuery
+                 if [ {{ validate.OperatingSystemName.outputs.stdout }} == 'alinux2' ]; then
+                   make
+                   /usr/local/{{ validate.CudaSamplesBinDir.outputs.stdout }}/sbsa/linux/release/deviceQuery | grep -o "Result = PASS"
+                 else
+                   if [ {{ validate.OperatingSystemName.outputs.stdout }} == 'ubuntu2004' ]; then
+                     MINI_CMAKE_VER_REQ=$(sed -n 's/cmake_minimum_required(\(VERSION \)\?\([0-9.]*\)).*/\2/p' CMakeLists.txt)
+                     COOKBOOK_ENV=$(jq '.default.cluster.cookbook_virtualenv_path' {{ CookbookDefaultFile }})
+                     COOKBOOK_ENV_PATH=$(echo ${COOKBOOK_ENV} | tr -d '\n' | cut -d = -f 2 | xargs)
+                     echo "Installing Cmake >= ${MINI_CMAKE_VER_REQ} in $COOKBOOK_ENV_PATH/bin"
+                     . $COOKBOOK_ENV_PATH/bin/activate
+                     $COOKBOOK_ENV_PATH/bin/pip3 install cmake>=$MINI_CMAKE_VER_REQ
+                     CMAKE_ARGS=""
+                     if [ -e $COOKBOOK_ENV_PATH/bin/cmake ]; then
+                       CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=$COOKBOOK_ENV_PATH/bin/cmake ${CMAKE_ARGS}"
+                     fi
                    fi
-                   [[ $? -ne 0 ]] && echo "CUDA deviceQuery test failed" && exit 1
-                fi
-                echo "CUDA deviceQuery test passed"
+                   mkdir build && cd build
+                   cmake .. \
+                    -DCMAKE_CUDA_ARCHITECTURES="75;80;86" \
+                    -DCMAKE_CUDA_COMPILER=/usr/local/cuda-${cuda_ver}/bin/nvcc \
+                    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-${cuda_ver} \
+                    -DCMAKE_PREFIX_PATH=/usr/local/cuda-cuda-${cuda_ver} \
+                     ${CMAKE_ARGS}
+                   make
+                   ./deviceQuery | grep -o "Result = PASS"
+                   if [ "${OS}" == 'ubuntu2004' ]; then
+                     $COOKBOOK_ENV_PATH/bin/pip3 uninstall cmake -y
+                     deactivate
+                   fi
+                 fi
+                 [[ $? -ne 0 ]] && echo "CUDA deviceQuery test failed" && exit 1
               fi
+              echo "CUDA deviceQuery test passed"
 
       - name: FSxLustre
         action: ExecuteBash
